[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts", "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "foundry-devops/=lib/foundry-devops"]
ffi = false

# Below sets amount of runs for Stateless Fuzz Testing
[fuzz]
runs = 150

# Below sets parameters for Stateful Fuzz Testing
[invariant]
runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
